### PR TITLE
chore: type error fix

### LINKED ISSUE #279: TypeError when withdrawing previous lock
Getting an error message when attempting to withdraw `$NATION` after the lock expiration date.

https://app.nation3.org/lock

> 

> 

```
TypeError: (u ?? []) is not iterable
```

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
fixes #279

### CODE REVIEW

**Review by aahna-ashina — CHANGES_REQUESTED** [review]
@abhisheknaiidu Is your git branch outdated? - https://citizen-app-mainnet-git-fork-abhisheknaiidu-main-nation3dao.vercel.app/liquidity

> image

**Comment by abhisheknaiidu** [comment]
@aahna-ashina now check once, i've updated it.

**Review by aahna-ashina — CHANGES_REQUESTED** [review]
@abhisheknaiidu Nothing happens when I click the button:
> 

But there is an error in the Console:
```
Uncaught (in promise) TypeError: y is not a function
    at 393-8620b5378a428cb4.js:1:2922
    at s (main-1d8adce4d7e8417e.js:1:89184)
    at Generator._invoke (main-1d8adce4d7e8417e.js:1:88972)
    at P.forEach.e.<computed> [as next] (main-1d8adce4d7e8417e.js:1:89607)
    at f (393-8620b5378a428cb4.js:1:2022)
    at s (393-8620b5378a428cb4.js:1:3189)
    at 393-8620b5378a428cb4.js:1:3248
    at new Promise (<anonymous>)
    at 393-8620b5378a428cb4.js:1:3129
    at 393-8620b5378a428cb4.js:1:3290
```

**Comment by aahna-ashina** [comment]
Fixed in https://github.com/nation3/citizen-app/pull/281

**Pull request closed without merging**
